[package]
name = "virtual_exec_type"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = "3.19.0"
inventory = "0.3.21"
ordered-float = "5.1.0"
paste = "1.0.15"
proc-macro2 = "1.0.103"
syn = "2.0.111"

